# clone to VPS
# install PM2 if no pm2
# run instance with PM2

name: Deploy Corelink Admin
on:
  push:
    branches: ["main"]

env:
  VPS_HOST: 161.97.184.247
  VPS_USER: root
  DEPLOY_DIR: /var/corelink/admin-frontend
  GIT_REPO: git@github.com:sulaimanahmed556-code/corelink-admin-dashboard.git
  PRIV_KEY: ${{secrets.CORELINK_SSH_PRIV_KEY}}
  DOMAIN_NAME: admin.coreliink.com
  BACKEND_BASE: https://app.coreliink.com

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{env.PRIV_KEY}}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{env.VPS_HOST}} >> ~/.ssh/known_hosts

      - name: Make Deply DEPLOY_DIR
        run: |
          ssh ${{env.VPS_USER}}@${{env.VPS_HOST}} "mkdir -p ${{env.DEPLOY_DIR}} && cd ${{env.DEPLOY_DIR}} && rm -rf ./* .[^.]* + && GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no' git clone ${{ env.GIT_REPO }} ." 

      


      - name: Build and Run, Nginx & SSL
        run: |

          ssh ${{ env.VPS_USER }}@${{ env.VPS_HOST }} bash << 'EOF'
          set -e

          cd ${{env.DEPLOY_DIR}}
          
          echo "VITE_API_URL=${{env.BACKEND_BASE}}">>.env

          npm install

          npm run build

          DEPLOY_DIR=${{ env.DEPLOY_DIR }}
          DOMAIN=${{ env.DOMAIN_NAME }}

          cd $DEPLOY_DIR

          echo "Installing Nginx if missing..."
          if ! command -v nginx >/dev/null 2>&1; then
              apt update && apt install -y nginx
          fi

          echo "Configuring Nginx reverse proxy..."

          NGINX_CONF="/etc/nginx/sites-available/$DOMAIN"

          cat > "$NGINX_CONF" << EOF_NGINX
          server {
              listen 80;
              server_name ${{ env.DOMAIN_NAME }};

              root ${{ env.DEPLOY_DIR }}/dist;
              index index.html;

              location / {
                  try_files \$uri \$uri /index.html;
               }
           }
          EOF_NGINX

          ln -sf "$NGINX_CONF" /etc/nginx/sites-enabled/
          nginx -t
          systemctl reload nginx

          echo "Installing Certbot if missing..."
          if ! command -v certbot >/dev/null 2>&1; then
              apt install -y certbot python3-certbot-nginx
          fi

          echo "Obtaining SSL certificate..."
          certbot --nginx -d $DOMAIN --non-interactive --agree-tos -m admin@$DOMAIN || true

          echo "Deployment complete."

          EOF
